language: c

cache:
  directories:
  - $HOME/.stack
  - .stack-work

# The different configurations we want to test.
#
# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
matrix:
  include:
  - env: ARGS="--resolver lts-6"
    compiler: ": #stack 7.10.3"
    addons: { apt: { packages: [libgmp-dev] } }

  - env: ARGS="--resolver lts-7"
    compiler: ": #stack 8.0.1"
    addons: { apt: { packages: [libgmp-dev] } }

  - env: ARGS="--resolver lts-8"
    compiler: ": #stack 8.0.2"
    addons: { apt: { packages: [libgmp-dev] } }

  - env: ARGS="--resolver nightly-2017-07-31"
    compiler: ": #stack 8.2.1"
    addons: { apt: { packages: [libgmp-dev] } }

  - env: ARGS="--resolver lts-11.22"
    compiler: ": #stack 8.2.2"
    addons: { apt: { packages: [libgmp-dev] } }

  - env: ARGS="--resolver lts-12.14"
    compiler: ": #stack 8.4.3"
    addons: { apt: { packages: [libgmp-dev] } }

  - env: ARGS="--resolver lts-12.26"
    compiler: ": #stack 8.4.4"
    addons: { apt: { packages: [libgmp-dev] } }

  - env: ARGS="--resolver lts-13.11"
    compiler: ": #stack 8.6.3"
    addons: { apt: { packages: [libgmp-dev] } }

  - env: ARGS="--resolver lts-13.19"
    compiler: ": #stack 8.6.4"
    addons: { apt: { packages: [libgmp-dev] } }

  - env: ARGS="--resolver lts-14.20"
    compiler: ": #stack 8.6.5"
    addons: { apt: { packages: [libgmp-dev] } }

  - env: ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons: { apt: { packages: [libgmp-dev] } }

  allow_failures:
  # Nightly builds are allowed to fail
  - env: ARGS="--resolver nightly"

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# Download and unpack the stack executable
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc $ARGS build happy
- stack --no-terminal $ARGS test --bench --only-dependencies

script:
- stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps --ghc-options=-Werror

before_cache:
- stack --no-terminal $ARGS clean monad-mock
